apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-gateway
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "10G"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - anduin-dev.experts.library.ucdavis.edu
    secretName: experts-wildcard-tls
  rules:
  - host: anduin-dev.experts.library.ucdavis.edu
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webapp-gateway
            port:
              number: 3000