apiVersion: apps/v1
kind: Deployment
metadata:
  name: dagster-code-server
spec:
  selector:
    matchLabels:
      app: dagster-code-server
  template:
    metadata:
      labels:
        app: dagster-code-server
    spec:
      containers:
      - name: service
        args: ["dagster", "code-server", "start", "-h", "0.0.0.0", "-p", "4000", "-f", "/opt/harvest/defs.py"]