apiVersion: apps/v1
kind: Deployment
metadata:
  name: anduin-gateway
spec:
  template:
    spec:
      containers:
        - name: service
          image: us-west1-docker.pkg.dev/aggie-experts/pub/anduin-gateway:anduin
      nodeSelector:
        intended-for: ae-dev-harvest