apiVersion: apps/v1
kind: Deployment
metadata:
  name: anduin-gateway
spec:
  template:
    spec:
      containers:
        - name: service
          image: us-west1-docker.pkg.dev/aggie-experts/pub/anduin-gateway:anduin
          env:
            - name: APP_URL
              value: "https://harvest-dev.experts.library.ucdavis.edu"
