apiVersion: apps/v1
kind: Deployment
metadata:
  name: dagster-celery-worker
spec:
  selector:
    matchLabels:
      app: dagster-celery-worker
  template:
    metadata:
      labels:
        app: dagster-celery-worker
    spec:
      containers:
      - name: service
        args: ["dagster-celery", "worker", "start", "-A", "dagster_celery.app", "-y", "/opt/dagster/dagster_home/celery_config.yaml"]