apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
  - path: service.yaml
    target:
      kind: Service
      name: dagster
    options:
      allowNameChange: true

  - path: deployment.yaml
    target:
      kind: Deployment
      name: dagster
    options:
      allowNameChange: true   