apiVersion: apps/v1
kind: Deployment
metadata:
  name: dagster-ui
spec:
  selector:
    matchLabels:
      app: dagster-ui
  template:
    metadata:
      labels:
        app: dagster-ui
    spec:
      containers:
      - name: service
        args: ["dagster-webserver", "--path-prefix", "/dagster", "-h", "0.0.0.0", "-p", "3000", "-w", "/opt/dagster/dagster_home/workspace.yaml"]
        ports:
        - containerPort: 3000