apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-api
spec:
  selector:
    matchLabels:
      app: webapp-api
  template:
    metadata:
      labels:
        app: webapp-api
    spec:
      containers:
      - name: service
        command: ["npm", "run", "api"]