apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-gateway
spec:
  selector:
    matchLabels:
      app: webapp-gateway
  template:
    metadata:
      labels:
        app: webapp-gateway
    spec:
      containers:
      - name: service
        command: ["npm", "run", "gateway"]
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          timeoutSeconds: 2
          periodSeconds: 5
          failureThreshold: 1